### ISSUE TITLE
Warning with gcc 8.1 [-Wclass-memaccess]

### ISSUE THREAD

**Issue by youtingxia** [Tencent/rapidjson#1246] opened 2018-05-10 07:18 UTC
g++ 8.1.0 (on CentOS 6.9), RapidJSON v1.1.0
rapidjson/document.h:1989:24: warning：‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘class rapidjson::GenericValue<rapidjson::UTF8<> >’ with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
             std::memcpy(e, values, count * sizeof(GenericValue));
             ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rapidjson/document.h:548:7: ‘class rapidjson::GenericValue<rapidjson::UTF8<> >’ declared here
 class GenericValue {

**Comment by janisozaur** [comment] 2018-05-10 12:51
Duplicate of https://github.com/Tencent/rapidjson/issues/1205

**Closed** 2018-07-16 04:22 UTC
