### ISSUE TITLE
Cmake 3.5 deprecation warning

### ISSUE THREAD

**Issue by Rinzii** [Tencent/rapidjson#2248] opened 2024-01-12 20:22 UTC
Currently RapidJson is using cmake 2.8.12 which is ancient even by cmake standards. I propose we upgrade the minimum cmake version to at least 3.6 to be inline with cmake and there deprecation warning.

**Comment by Chronial** [comment] 2024-01-15 06:35
Duplicate of #2159

**Closed** 2024-01-18 05:17 UTC
