### ISSUE TITLE
No more official release?

### ISSUE THREAD

**Issue by milipili** [Tencent/rapidjson#1626] opened 2019-12-18 01:00 UTC
The last release is tagged from 2016.... :)

**Comment by arghness** [comment] 2019-12-19 17:22
Duplicate of #1006

**Closed** 2019-12-20 15:01 UTC

**Comment by Livius90** [comment] 2022-01-16 11:42
Use nlohmann C++ json lib, it is much better in releasing and documentation. I gave up waiting for new rapidjson release, i am using this other from now.
https://github.com/nlohmann/json
