### ISSUE TITLE
Need an amalgamation?

### ISSUE THREAD

**Issue by shawn-dev** [Tencent/rapidjson#705] opened 2016-08-04 09:24 UTC
Hi miloyip,

Do you have a plan to make an amalgamation of all the headers?
I think single header file is cool.

It will be much easier to use, and compile time may be a littler longer, though.

**Comment by juj** [comment] 2018-09-08 20:47
Looks like there is an unofficial node.js based script posted in #863 that solves this, perhaps this can be closed as duplicate of that discussion.

**Closed** 2018-09-14 03:08 UTC
