### ISSUE TITLE
Next Release Date?

### ISSUE THREAD

**Issue by ultimo-hombre** [Tencent/rapidjson#1911] opened 2021-07-02 02:08 UTC
There are 630 commits since the last release, v1.1.0. When is the next release planned?

**Comment by ks1322** [comment] 2021-07-06 10:51
Duplicate of #1881, #1862, #1820, #1774, #1006

**Closed** 2021-07-10 15:26 UTC

**Comment by gvollant** [comment] 2021-09-19 07:53
Duplicate are #1919 #1006 #1130 #1341 #1896 #1911

@miloyip rapidjson is really a very wonderfull library

I had to migrate from current release to a "last git" version for c++17 compatibility issues.

A lot of people think a new release with current code is needed !!
